version: '3.4'

services:
  mongo: 
    image: mongo
    restart: always
    ports:
     - 27017:27017
    networks:
     - test

  rabbit: 
    image: rabbitmq:3.7-management
    ports:
     - 5672:5672
     - 15672:15672
    networks:
     - test 
 
  eureka: 
    image: springcloud/eureka
    ports:
     - 8761:8761
    networks:
     - test
      
  mongo-client:
    image: mongoclient/mongoclient
    ports:
     - 3000:3000
    networks:
     - test
    
  redis:
    image: redis
    ports:
     - 6379:6379
    networks:
     - test

  castle-mock:
    image: castlemock/castlemock
    ports:
     - 4000:8080
     networks:
     - test
